### ISSUE TITLE
Frameworks para BDD

### ISSUE THREAD

**Issue by mrlucasrib** [mrlucasrib/QChicken#12]
Foi sugerido pelo professor que usássemos o Cucumber, porém ele é baseado em expressão regular e é muito trabalhoso para implementar. Por conta do prazo curto, sugiro usarmos o Squish, que resolve nosso problema e não adiciona complexidade desnecessária ao projeto. Deem sugestões e opiniões.

**Comment by pedroeuzebio** [comment]
ao que parece o Squish é mais prático e não perderemos funcionalidades do Cucumber. Como você mesmo disse, o prazo é curto, seria melhor entregarmos algo completo usando o Squish na minha opinião

**Comment by thborba** [comment]
Concordo com vocês, acho que o Squish vai atender muito bem ao que a gente precisa. Acho que devemos usar ele mesmo.
