### ISSUE TITLE
CMake ou Qmake, qual utilizar?

### ISSUE THREAD

**Issue by mrlucasrib** [mrlucasrib/QChicken#2]
## Devemos decidir qual dois dois iremos utilizar no projeto.
Eu prefiro o CMake por ter integrações prontas no Github Actions. Utilizando o qmake precisaremos escrever nossas próprias Actions.
**Deem suas opiniões nesta issue.**

**Comment by pedroeuzebio** [comment]
> ## Devemos decidir qual dois dois iremos utilizar no projeto.
> Eu prefiro o CMake por ter integrações prontas no Github Actions. Utilizando o qmake precisaremos escrever nossas próprias Actions.
> **Deem suas opiniões nesta issue.**

Acho válido o uso do CMake por esse motivo, não vejo nenhum problema em utilizá-lo em detrimento do qmake
