### ISSUE TITLE
Qual framework de testes utilizar?

### ISSUE THREAD

**Issue by mrlucasrib** [mrlucasrib/QChicken#7]
Devemos definir o Framework a ser utilizado. Algumas opções são: Google Test, Qt Test, CppTest, etc.

**Comment by thborba** [comment]
Acho que o Qt Test é uma boa

**Comment by pedroeuzebio** [comment]
> Devemos definir o Framework a ser utilizado. Algumas opções são: Google Test, Qt Test, CppTest, etc.

O Google test parece ser uma boa, pelo o que pesquisei ele consegue satisfazer as necessidades do nosso projeto, mas o qt test tbm parece ser bom
